(setq mm-text-html-renderer 'w3m-standalone)
(setq mm-verify-option 'known)
(setq mm-decrypt-option 'known)
(setq smtpmail-debug-info t)
(setq gnus-treat-body-boundary 'head)
(setq gnus-body-boundary-delimiter "–")
(setq gnus-treat-hide-signature t)
(setq gnus-treat-date-local 'head)
(setq gnus-treat-date-lapsed 'head)
(setq gnus-article-date-lapsed-new-header t)
(setq gnus-inhibit-startup-message t)
(setq user-mail-address "dominikh@fork-bomb.org")
(setq smtpmail-debug-verb t)
(setq message-send-mail-function 'message-send-mail-with-sendmail)
(setq sendmail-program "/usr/bin/msmtp")
(setq message-sendmail-extra-arguments '("-a" "fork-bomb"))

(defun gnus-goto-google ()
  (interactive)
  (when (memq major-mode '(gnus-summary-mode gnus-article-mode))
    (when (eq major-mode 'gnus-article-mode)
      (gnus-article-show-summary))
    (let* ((article (gnus-summary-article-number))
           (header (gnus-summary-article-header article))
           (id (substring (mail-header-id header) 1 -1)))
      (kill-new
       (format "http://groups.google.com/groups?selm=%s" id)))))
