(add-to-list 'load-path "~/.emacs.d/contrib/yasnippet")
(add-to-list 'load-path "~/.emacs.d")
(add-to-list 'load-path "~/.emacs.d/contrib")
(add-to-list 'load-path "~/.emacs.d/contrib/magit")
(add-to-list 'load-path "~/.emacs.d/contrib/emacs-rails")
(add-to-list 'load-path "~/.emacs.d/contrib/gnuplot-mode")
(add-to-list 'load-path "~/.emacs.d/contrib/bbdb/lisp")
(add-to-list 'load-path "~/.emacs.d/contrib/mo-git-blame")
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp")
(add-to-list 'load-path "~/.emacs.d/contrib/html5-el/")
(add-to-list 'load-path "~/.emacs.d/contrib/gnus/lisp")
(add-to-list 'load-path "~/go/misc/emacs/")

